// TODO: replace all exports with Supabase queries

// TODO: query users table with role join
export const mockUsers = [
  { id: '1', name: 'María Santos', role: 'learner', avatar: 'MS', joined: '2025-01-15' },
  { id: '2', name: 'Carlos Rivera', role: 'contributor', avatar: 'CR', joined: '2024-11-02' },
  { id: '3', name: 'Ana Pérez', role: 'expert', area: 'JavaScript', avatar: 'AP', joined: '2024-06-20' },
  { id: '4', name: 'Luis Martínez', role: 'admin', avatar: 'LM', joined: '2024-01-01' },
  { id: '5', name: 'Pedro Herrera', role: 'learner', avatar: 'PH', joined: '2025-02-08' },
  { id: '6', name: 'Sofía Núñez', role: 'contributor', avatar: 'SN', joined: '2024-12-14' },
  { id: '7', name: 'Roberto Cruz', role: 'expert', area: 'DevOps', avatar: 'RC', joined: '2024-08-03' },
  { id: '8', name: 'Carmen López', role: 'expert', area: 'Data Science', avatar: 'CL', joined: '2024-09-11' },
]

// TODO: query courses table with co_authors join
export const courses = [
  {
    id: 'c1',
    title: { en: 'Introduction to Web Development', es: 'Introducción al Desarrollo Web' },
    description: {
      en: 'Build your first website from scratch. Learn HTML, CSS, and JavaScript fundamentals with hands-on projects.',
      es: 'Construye tu primer sitio web desde cero. Aprende HTML, CSS y JavaScript con proyectos prácticos.',
    },
    level: 'beginner',
    modules: 12,
    duration: '6 weeks',
    youtubeId: 'G3e-cpL7ofc',
    youtubePlaylist: 'PLZlA0Gpn_vH8jbFkBjOumy_gLFpVZFKL',
    coAuthors: [{ id: '3', name: 'Ana Pérez', avatar: 'AP' }],
    enrolled: 234,
    tags: ['html', 'css', 'javascript'],
    status: 'published',
    lang: 'both',
    createdAt: '2025-01-10',
  },
  {
    id: 'c2',
    title: { en: 'Python for Data Science', es: 'Python para Ciencia de Datos' },
    description: {
      en: 'Master Python for data analysis, visualization, and machine learning basics.',
      es: 'Domina Python para análisis de datos, visualización y fundamentos de machine learning.',
    },
    level: 'intermediate',
    modules: 18,
    duration: '8 weeks',
    youtubeId: 'LHBE0uhFjHI',
    youtubePlaylist: null,
    coAuthors: [{ id: '8', name: 'Carmen López', avatar: 'CL' }],
    enrolled: 189,
    tags: ['python', 'data', 'pandas', 'numpy'],
    status: 'published',
    lang: 'es',
    createdAt: '2025-02-01',
  },
  {
    id: 'c3',
    title: { en: 'Git & GitHub Fundamentals', es: 'Fundamentos de Git y GitHub' },
    description: {
      en: 'Version control from zero to hero. Branching, merging, PRs, and team workflows.',
      es: 'Control de versiones de cero a experto. Ramas, merges, PRs y flujos de trabajo en equipo.',
    },
    level: 'beginner',
    modules: 8,
    duration: '3 weeks',
    youtubeId: 'RGOj5yH7evk',
    youtubePlaylist: null,
    coAuthors: [{ id: '2', name: 'Carlos Rivera', avatar: 'CR' }],
    enrolled: 412,
    tags: ['git', 'github', 'versioncontrol'],
    status: 'published',
    lang: 'en',
    createdAt: '2024-11-15',
  },
  {
    id: 'c4',
    title: { en: 'SQL for Beginners', es: 'SQL para Principiantes' },
    description: {
      en: 'Query databases with confidence. SELECT, JOIN, GROUP BY, and more — real projects included.',
      es: 'Consulta bases de datos con confianza. SELECT, JOIN, GROUP BY y más — con proyectos reales.',
    },
    level: 'beginner',
    modules: 10,
    duration: '4 weeks',
    youtubeId: 'HXV3zeQKqGY',
    youtubePlaylist: null,
    coAuthors: [],
    enrolled: 97,
    tags: ['sql', 'databases', 'postgresql'],
    status: 'published',
    lang: 'en',
    createdAt: '2025-03-05',
  },
  {
    id: 'c5',
    title: { en: 'Docker & Containers Crash Course', es: 'Curso Intensivo de Docker y Contenedores' },
    description: {
      en: 'Containerize everything. Understand Docker images, volumes, compose, and deployment basics.',
      es: 'Conteneriza todo. Entiende imágenes Docker, volúmenes, compose y fundamentos de despliegue.',
    },
    level: 'intermediate',
    modules: 9,
    duration: '4 weeks',
    youtubeId: 'fqMOX6JJhGo',
    youtubePlaylist: null,
    coAuthors: [{ id: '7', name: 'Roberto Cruz', avatar: 'RC' }],
    enrolled: 76,
    tags: ['docker', 'devops', 'containers'],
    status: 'published',
    lang: 'both',
    createdAt: '2025-03-20',
  },
  {
    id: 'c6',
    title: { en: 'Advanced JavaScript: Async & Patterns', es: 'JavaScript Avanzado: Async y Patrones' },
    description: {
      en: 'Deep dive into Promises, async/await, event loop, design patterns, and modern JS tooling.',
      es: 'Profundiza en Promises, async/await, event loop, patrones de diseño y herramientas modernas.',
    },
    level: 'advanced',
    modules: 15,
    duration: '7 weeks',
    youtubeId: null,
    youtubePlaylist: null,
    coAuthors: [{ id: '3', name: 'Ana Pérez', avatar: 'AP' }],
    enrolled: 143,
    tags: ['javascript', 'async', 'patterns'],
    status: 'published',
    lang: 'both',
    createdAt: '2025-04-01',
  },
]

// TODO: query kb_articles table with maintainer join
export const kbArticles = [
  {
    id: 'kb1',
    title: { en: 'Setting Up VS Code for Web Development', es: 'Configurar VS Code para Desarrollo Web' },
    summary: {
      en: 'Extensions, settings, and shortcuts to make VS Code your perfect web dev environment.',
      es: 'Extensiones, configuraciones y atajos para hacer de VS Code tu entorno perfecto de desarrollo web.',
    },
    content: {
      en: 'VS Code is the most popular code editor for web development...',
      es: 'VS Code es el editor de código más popular para el desarrollo web...',
    },
    category: 'tools',
    status: 'verified',
    maintainer: { id: '3', name: 'Ana Pérez', avatar: 'AP' },
    tags: ['vscode', 'tools', 'setup'],
    views: 1204,
    updatedAt: '2025-04-10',
  },
  {
    id: 'kb2',
    title: { en: 'Understanding REST APIs', es: 'Entendiendo las APIs REST' },
    summary: {
      en: 'What REST is, how HTTP verbs work, status codes, and how to design clean endpoints.',
      es: 'Qué es REST, cómo funcionan los verbos HTTP, códigos de estado y cómo diseñar endpoints limpios.',
    },
    content: {
      en: 'REST (Representational State Transfer) is an architectural style...',
      es: 'REST (Representational State Transfer) es un estilo arquitectónico...',
    },
    category: 'webdev',
    status: 'verified',
    maintainer: { id: '2', name: 'Carlos Rivera', avatar: 'CR' },
    tags: ['rest', 'api', 'http'],
    views: 876,
    updatedAt: '2025-03-28',
  },
  {
    id: 'kb3',
    title: { en: 'Git Commands Cheatsheet', es: 'Cheatsheet de Comandos Git' },
    summary: {
      en: 'The most-used Git commands with examples: init, clone, commit, push, pull, branch, merge.',
      es: 'Los comandos Git más usados con ejemplos: init, clone, commit, push, pull, branch, merge.',
    },
    content: {
      en: 'This cheatsheet covers the 20 most important Git commands...',
      es: 'Este cheatsheet cubre los 20 comandos Git más importantes...',
    },
    category: 'tools',
    status: 'verified',
    maintainer: { id: '2', name: 'Carlos Rivera', avatar: 'CR' },
    tags: ['git', 'cheatsheet'],
    views: 2341,
    updatedAt: '2025-02-14',
  },
  {
    id: 'kb4',
    title: { en: 'CSS Grid Layout Guide', es: 'Guía de CSS Grid Layout' },
    summary: {
      en: 'Complete reference for CSS Grid: grid-template, areas, auto-fill, minmax, and responsive patterns.',
      es: 'Referencia completa de CSS Grid: grid-template, áreas, auto-fill, minmax y patrones responsivos.',
    },
    content: {
      en: 'CSS Grid is a two-dimensional layout system...',
      es: 'CSS Grid es un sistema de diseño bidimensional...',
    },
    category: 'webdev',
    status: 'review',
    maintainer: { id: '3', name: 'Ana Pérez', avatar: 'AP' },
    tags: ['css', 'grid', 'layout'],
    views: 654,
    updatedAt: '2025-04-20',
  },
  {
    id: 'kb5',
    title: { en: 'Docker Basics: Images and Containers', es: 'Fundamentos de Docker: Imágenes y Contenedores' },
    summary: {
      en: 'Understand the difference between images and containers, how to build, run, and stop them.',
      es: 'Entiende la diferencia entre imágenes y contenedores, cómo construirlos, ejecutarlos y detenerlos.',
    },
    content: {
      en: 'Docker is a platform for developing, shipping, and running applications...',
      es: 'Docker es una plataforma para desarrollar, enviar y ejecutar aplicaciones...',
    },
    category: 'devops',
    status: 'draft',
    maintainer: null,
    tags: ['docker', 'devops', 'containers'],
    views: 123,
    updatedAt: '2025-04-25',
  },
  {
    id: 'kb6',
    title: { en: 'Python Virtual Environments', es: 'Entornos Virtuales de Python' },
    summary: {
      en: 'Why you need venv, how to create and activate one, and managing dependencies with pip.',
      es: 'Por qué necesitas venv, cómo crear y activar uno, y gestionar dependencias con pip.',
    },
    content: {
      en: 'A virtual environment is an isolated Python environment...',
      es: 'Un entorno virtual es un entorno Python aislado...',
    },
    category: 'tools',
    status: 'draft',
    maintainer: null,
    tags: ['python', 'venv', 'pip'],
    views: 89,
    updatedAt: '2025-04-28',
  },
  {
    id: 'kb7',
    title: { en: 'SQL JOINs Explained', es: 'Las JOINs de SQL Explicadas' },
    summary: {
      en: 'INNER, LEFT, RIGHT, and FULL JOIN with visual diagrams and real-world examples.',
      es: 'INNER, LEFT, RIGHT y FULL JOIN con diagramas visuales y ejemplos del mundo real.',
    },
    content: {
      en: 'SQL JOINs allow you to combine rows from two or more tables...',
      es: 'Las JOINs de SQL te permiten combinar filas de dos o más tablas...',
    },
    category: 'data',
    status: 'verified',
    maintainer: { id: '8', name: 'Carmen López', avatar: 'CL' },
    tags: ['sql', 'databases', 'joins'],
    views: 1087,
    updatedAt: '2025-03-10',
  },
  {
    id: 'kb8',
    title: { en: 'Career Roadmap: Junior Developer', es: 'Hoja de Ruta: Desarrollador Junior' },
    summary: {
      en: 'Skills, projects, and milestones to land your first dev job. Built from community experience.',
      es: 'Habilidades, proyectos e hitos para conseguir tu primer trabajo como desarrollador.',
    },
    content: {
      en: 'The path to your first developer job is clearer than you think...',
      es: 'El camino a tu primer trabajo como desarrollador es más claro de lo que piensas...',
    },
    category: 'career',
    status: 'review',
    maintainer: null,
    tags: ['career', 'roadmap', 'junior'],
    views: 445,
    updatedAt: '2025-04-15',
  },
]

// TODO: query experts table with user join
export const expertSlots = [
  {
    area: 'JavaScript',
    areaEs: 'JavaScript',
    icon: '⚡',
    filled: true,
    expert: { id: '3', name: 'Ana Pérez', avatar: 'AP', articles: 4, courses: 2, bio: { en: 'JavaScript educator and open-source contributor.', es: 'Educadora de JavaScript y contribuidora de código abierto.' } },
  },
  {
    area: 'Python',
    areaEs: 'Python',
    icon: '🐍',
    filled: false,
    expert: null,
  },
  {
    area: 'DevOps',
    areaEs: 'DevOps',
    icon: '🚀',
    filled: true,
    expert: { id: '7', name: 'Roberto Cruz', avatar: 'RC', articles: 3, courses: 1, bio: { en: 'Cloud & DevOps engineer with 8 years of experience.', es: 'Ingeniero de Cloud y DevOps con 8 años de experiencia.' } },
  },
  {
    area: 'Data Science',
    areaEs: 'Ciencia de Datos',
    icon: '📊',
    filled: true,
    expert: { id: '8', name: 'Carmen López', avatar: 'CL', articles: 5, courses: 1, bio: { en: 'Data scientist passionate about democratizing data education.', es: 'Científica de datos apasionada por democratizar la educación en datos.' } },
  },
  {
    area: 'UI/UX Design',
    areaEs: 'Diseño UI/UX',
    icon: '🎨',
    filled: false,
    expert: null,
  },
  {
    area: 'Cybersecurity',
    areaEs: 'Ciberseguridad',
    icon: '🔐',
    filled: false,
    expert: null,
  },
  {
    area: 'Mobile Development',
    areaEs: 'Desarrollo Móvil',
    icon: '📱',
    filled: false,
    expert: null,
  },
  {
    area: 'Databases',
    areaEs: 'Bases de Datos',
    icon: '🗄️',
    filled: false,
    expert: null,
  },
]

// TODO: query open_requests table with user and status join
export const openRequests = [
  {
    id: 'r1',
    type: 'module',
    title: { en: 'React Hooks Explained — useEffect deep dive', es: 'React Hooks Explicados — useEffect a fondo' },
    description: {
      en: 'Need a clear video module explaining useEffect dependencies, cleanup functions, and common pitfalls.',
      es: 'Necesitamos un módulo de video claro explicando las dependencias de useEffect, funciones de limpieza y errores comunes.',
    },
    status: 'open',
    postedBy: { id: '1', name: 'María Santos', avatar: 'MS' },
    watchers: 14,
    course: 'c6',
    postedAt: '2025-04-20',
  },
  {
    id: 'r2',
    type: 'article',
    title: { en: 'Docker Compose: Multi-service Apps', es: 'Docker Compose: Aplicaciones Multi-servicio' },
    description: {
      en: 'We need a KB article covering docker-compose.yml structure, networking between services, and env vars.',
      es: 'Necesitamos un artículo de KB cubriendo la estructura de docker-compose.yml, redes entre servicios y variables de entorno.',
    },
    status: 'open',
    postedBy: { id: '7', name: 'Roberto Cruz', avatar: 'RC' },
    watchers: 8,
    course: null,
    postedAt: '2025-04-22',
  },
  {
    id: 'r3',
    type: 'review',
    title: { en: 'Peer Review: CSS Grid Layout Guide', es: 'Revisión: Guía de CSS Grid Layout' },
    description: {
      en: 'The CSS Grid article (kb4) is in review. Looking for someone to fact-check and suggest improvements.',
      es: 'El artículo de CSS Grid (kb4) está en revisión. Buscamos a alguien que verifique los hechos y sugiera mejoras.',
    },
    status: 'open',
    postedBy: { id: '3', name: 'Ana Pérez', avatar: 'AP' },
    watchers: 5,
    article: 'kb4',
    postedAt: '2025-04-23',
  },
  {
    id: 'r4',
    type: 'answer',
    title: { en: 'How do I center a div with CSS?', es: '¿Cómo centro un div con CSS?' },
    description: {
      en: 'Classic question in thread t1. Someone with solid CSS knowledge should give a verified answer.',
      es: 'Pregunta clásica en el hilo t1. Alguien con conocimiento sólido de CSS debería dar una respuesta verificada.',
    },
    status: 'claimed',
    postedBy: { id: '5', name: 'Pedro Herrera', avatar: 'PH' },
    claimedBy: { id: '3', name: 'Ana Pérez', avatar: 'AP' },
    watchers: 22,
    thread: 't1',
    postedAt: '2025-04-18',
  },
  {
    id: 'r5',
    type: 'module',
    title: { en: 'SQL Transactions & ACID Properties', es: 'Transacciones SQL y Propiedades ACID' },
    description: {
      en: 'A module explaining BEGIN, COMMIT, ROLLBACK, and the ACID properties with practical examples.',
      es: 'Un módulo explicando BEGIN, COMMIT, ROLLBACK y las propiedades ACID con ejemplos prácticos.',
    },
    status: 'open',
    postedBy: { id: '2', name: 'Carlos Rivera', avatar: 'CR' },
    watchers: 11,
    course: 'c4',
    postedAt: '2025-04-25',
  },
  {
    id: 'r6',
    type: 'article',
    title: { en: 'Introduction to TypeScript for JS Developers', es: 'Introducción a TypeScript para Desarrolladores JS' },
    description: {
      en: 'A beginner-friendly KB article covering types, interfaces, generics, and migrating from JS.',
      es: 'Un artículo amigable para principiantes cubriendo tipos, interfaces, genéricos y migración desde JS.',
    },
    status: 'open',
    postedBy: { id: '6', name: 'Sofía Núñez', avatar: 'SN' },
    watchers: 17,
    course: null,
    postedAt: '2025-04-26',
  },
  {
    id: 'r7',
    type: 'review',
    title: { en: 'Peer Review: Python Virtual Environments article', es: 'Revisión: Artículo de Entornos Virtuales de Python' },
    description: {
      en: 'Draft article (kb6) needs review. Python expertise helpful but not required.',
      es: 'El artículo borrador (kb6) necesita revisión. Experiencia en Python útil pero no necesaria.',
    },
    status: 'open',
    postedBy: { id: '8', name: 'Carmen López', avatar: 'CL' },
    watchers: 3,
    article: 'kb6',
    postedAt: '2025-04-28',
  },
  {
    id: 'r8',
    type: 'answer',
    title: { en: 'Best way to handle async errors in Node.js?', es: '¿Mejor manera de manejar errores async en Node.js?' },
    description: {
      en: 'Thread t3 has this unanswered. Need someone with Node.js experience to write the canonical answer.',
      es: 'El hilo t3 tiene esto sin respuesta. Necesitamos a alguien con experiencia en Node.js para escribir la respuesta oficial.',
    },
    status: 'open',
    postedBy: { id: '2', name: 'Carlos Rivera', avatar: 'CR' },
    watchers: 9,
    thread: 't3',
    postedAt: '2025-04-29',
  },
]

// TODO: query threads table with replies and expert_answers join
export const communityThreads = [
  {
    id: 't1',
    title: { en: 'How do I center a div in CSS?', es: '¿Cómo centro un div en CSS?' },
    body: {
      en: 'I\'ve been struggling with this forever. Is Flexbox the go-to in 2025? What about Grid? When should I use each?',
      es: 'Llevo tiempo luchando con esto. ¿Es Flexbox lo ideal en 2025? ¿Qué hay de Grid? ¿Cuándo uso cada uno?',
    },
    postedBy: { id: '5', name: 'Pedro Herrera', avatar: 'PH' },
    views: 284,
    replies: 12,
    expertAnswer: {
      by: { id: '3', name: 'Ana Pérez', avatar: 'AP' },
      text: {
        en: 'Use Flexbox for one-dimensional centering, Grid for two-dimensional. For the classic "center everything" case: `display: flex; justify-content: center; align-items: center;` on the parent.',
        es: 'Usa Flexbox para centrado unidimensional, Grid para bidimensional. Para el caso clásico: `display: flex; justify-content: center; align-items: center;` en el padre.',
      },
    },
    tags: ['css', 'flexbox', 'grid'],
    postedAt: '2025-04-15',
    hot: true,
  },
  {
    id: 't2',
    title: { en: 'Best resources for learning React in 2025?', es: '¿Mejores recursos para aprender React en 2025?' },
    body: {
      en: 'Looking for up-to-date resources. The React docs are good but I\'d love community recommendations too.',
      es: 'Buscando recursos actualizados. La documentación de React es buena pero también quiero recomendaciones de la comunidad.',
    },
    postedBy: { id: '1', name: 'María Santos', avatar: 'MS' },
    views: 156,
    replies: 5,
    expertAnswer: null,
    tags: ['react', 'resources', 'learning'],
    postedAt: '2025-04-19',
    hot: false,
  },
  {
    id: 't3',
    title: { en: 'How to deploy a Node.js app to a VPS?', es: '¿Cómo desplegar una app Node.js en un VPS?' },
    body: {
      en: 'I have a Node.js app working locally. What\'s the recommended way to deploy it? I\'m thinking PM2 + Nginx but not sure about the full setup.',
      es: 'Tengo una app Node.js funcionando localmente. ¿Cuál es la forma recomendada de desplegarla? Estoy pensando en PM2 + Nginx pero no estoy seguro del proceso completo.',
    },
    postedBy: { id: '6', name: 'Sofía Núñez', avatar: 'SN' },
    views: 98,
    replies: 8,
    expertAnswer: {
      by: { id: '7', name: 'Roberto Cruz', avatar: 'RC' },
      text: {
        en: 'PM2 + Nginx is the classic stack. Steps: 1) Deploy your code via Git, 2) Run `pm2 start app.js`, 3) Configure Nginx as a reverse proxy to port 3000, 4) Set up SSL with Certbot.',
        es: 'PM2 + Nginx es el stack clásico. Pasos: 1) Despliega tu código via Git, 2) Ejecuta `pm2 start app.js`, 3) Configura Nginx como proxy inverso al puerto 3000, 4) Configura SSL con Certbot.',
      },
    },
    tags: ['nodejs', 'devops', 'deployment', 'vps'],
    postedAt: '2025-04-22',
    hot: true,
  },
  {
    id: 't4',
    title: { en: 'Git rebase vs merge — when to use which?', es: 'Git rebase vs merge — ¿cuándo usar cuál?' },
    body: {
      en: 'My team argues about this constantly. Is there a definitive answer or is it team preference?',
      es: 'Mi equipo discute sobre esto constantemente. ¿Hay una respuesta definitiva o es preferencia del equipo?',
    },
    postedBy: { id: '2', name: 'Carlos Rivera', avatar: 'CR' },
    views: 211,
    replies: 17,
    expertAnswer: null,
    tags: ['git', 'workflow', 'teams'],
    postedAt: '2025-04-10',
    hot: false,
  },
  {
    id: 't5',
    title: { en: 'Is SQL still worth learning in 2025?', es: '¿Vale la pena aprender SQL en 2025?' },
    body: {
      en: 'With all the ORMs and NoSQL databases around, I wonder if raw SQL knowledge is still important for a junior dev.',
      es: 'Con todos los ORMs y bases de datos NoSQL disponibles, me pregunto si el conocimiento de SQL puro sigue siendo importante para un junior.',
    },
    postedBy: { id: '1', name: 'María Santos', avatar: 'MS' },
    views: 334,
    replies: 23,
    expertAnswer: {
      by: { id: '8', name: 'Carmen López', avatar: 'CL' },
      text: {
        en: 'Absolutely. SQL is the lingua franca of data. Even with ORMs you\'ll need to debug queries. For data roles it\'s non-negotiable. Learn it early, thank yourself later.',
        es: 'Absolutamente. SQL es la lengua franca de los datos. Incluso con ORMs necesitarás depurar consultas. Para roles de datos es innegociable. Aprende pronto, agradécetelo después.',
      },
    },
    tags: ['sql', 'career', 'databases'],
    postedAt: '2025-04-08',
    hot: true,
  },
]

// TODO: query activity_events table with user join
export const activityFeed = [
  { id: 'af1', avatar: 'AP', name: 'Ana Pérez', event: { en: 'verified the article "Setting Up VS Code"', es: 'verificó el artículo "Configurar VS Code"' }, time: { en: '2 minutes ago', es: 'hace 2 minutos' } },
  { id: 'af2', avatar: 'RC', name: 'Roberto Cruz', event: { en: 'posted a new expert answer in the Node.js deployment thread', es: 'publicó una nueva respuesta de experto en el hilo de despliegue Node.js' }, time: { en: '14 minutes ago', es: 'hace 14 minutos' } },
  { id: 'af3', avatar: 'MS', name: 'María Santos', event: { en: 'enrolled in "Introduction to Web Development"', es: 'se inscribió en "Introducción al Desarrollo Web"' }, time: { en: '1 hour ago', es: 'hace 1 hora' } },
  { id: 'af4', avatar: 'SN', name: 'Sofía Núñez', event: { en: 'posted a new thread: "How to deploy a Node.js app?"', es: 'publicó un nuevo hilo: "¿Cómo desplegar una app Node.js?"' }, time: { en: '2 hours ago', es: 'hace 2 horas' } },
  { id: 'af5', avatar: 'CR', name: 'Carlos Rivera', event: { en: 'claimed the Open Request: SQL Transactions module', es: 'tomó la Solicitud Abierta: módulo de Transacciones SQL' }, time: { en: '3 hours ago', es: 'hace 3 horas' } },
  { id: 'af6', avatar: 'CL', name: 'Carmen López', event: { en: 'published a new KB article: "SQL JOINs Explained"', es: 'publicó un nuevo artículo KB: "Las JOINs de SQL Explicadas"' }, time: { en: '5 hours ago', es: 'hace 5 horas' } },
  { id: 'af7', avatar: 'PH', name: 'Pedro Herrera', event: { en: 'started watching Open Request: React Hooks module', es: 'comenzó a seguir la Solicitud Abierta: módulo de React Hooks' }, time: { en: '6 hours ago', es: 'hace 6 horas' } },
]

// TODO: query platform_stats view
export const communityStats = [
  { key: 'home.pulse.learners', value: '847', icon: '🎓' },
  { key: 'home.pulse.contributors', value: '23', icon: '✍️' },
  { key: 'home.pulse.experts', value: '5', icon: '⭐' },
  { key: 'home.pulse.articles', value: '67', icon: '📄' },
  { key: 'home.pulse.requests', value: '8', icon: '🔓' },
  { key: 'home.pulse.threads', value: '1,204', icon: '💬' },
]

// TODO: query admin_stats view (admin only)
export const adminStats = {
  totalUsers: 877,
  learners: 847,
  contributors: 23,
  experts: 5,
  admins: 2,
  totalCourses: 6,
  publishedCourses: 6,
  totalArticles: 67,
  verifiedArticles: 42,
  draftArticles: 15,
  inReviewArticles: 10,
  openRequests: 8,
  pendingModeration: 3,
  threadsTotal: 1204,
  monthlyActiveUsers: 312,
}

// TODO: query moderation_queue table
export const moderationQueue = [
  {
    id: 'm1',
    type: 'thread',
    title: { en: 'Promoted content post', es: 'Publicación de contenido promocionado' },
    submittedBy: { id: '5', name: 'Pedro Herrera', avatar: 'PH' },
    flag: { en: 'Possible spam', es: 'Posible spam' },
    submittedAt: '2025-04-29',
  },
  {
    id: 'm2',
    type: 'article',
    title: { en: 'CSS Flexbox Cheatsheet', es: 'Cheatsheet de CSS Flexbox' },
    submittedBy: { id: '6', name: 'Sofía Núñez', avatar: 'SN' },
    flag: { en: 'Needs expert review', es: 'Necesita revisión de experto' },
    submittedAt: '2025-04-28',
  },
  {
    id: 'm3',
    type: 'request',
    title: { en: 'Request with missing context', es: 'Solicitud con contexto faltante' },
    submittedBy: { id: '1', name: 'María Santos', avatar: 'MS' },
    flag: { en: 'Incomplete description', es: 'Descripción incompleta' },
    submittedAt: '2025-04-27',
  },
]
